// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0sb7aQtn1-fwbURSZ69TS3e7MK8l7vRQ',
    appId: '1:644563189108:web:d2fc068199e70491550021',
    messagingSenderId: '644563189108',
    projectId: 'carmatchup',
    authDomain: 'carmatchup.firebaseapp.com',
    storageBucket: 'carmatchup.appspot.com',
    measurementId: 'G-XD6FS0WCXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDckaEniODFwBKhApIVnNKIR8L5JogKdS0',
    appId: '1:644563189108:android:32bdbd8f2e19fdef550021',
    messagingSenderId: '644563189108',
    projectId: 'carmatchup',
    storageBucket: 'carmatchup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8T5V3kEOsN_-jdWvs565aYYFEJ1mKl5w',
    appId: '1:644563189108:ios:8b9e27fed39b5812550021',
    messagingSenderId: '644563189108',
    projectId: 'carmatchup',
    storageBucket: 'carmatchup.appspot.com',
    iosBundleId: 'com.example.carMatchup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8T5V3kEOsN_-jdWvs565aYYFEJ1mKl5w',
    appId: '1:644563189108:ios:8b9e27fed39b5812550021',
    messagingSenderId: '644563189108',
    projectId: 'carmatchup',
    storageBucket: 'carmatchup.appspot.com',
    iosBundleId: 'com.example.carMatchup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0sb7aQtn1-fwbURSZ69TS3e7MK8l7vRQ',
    appId: '1:644563189108:web:578cebd4072e1862550021',
    messagingSenderId: '644563189108',
    projectId: 'carmatchup',
    authDomain: 'carmatchup.firebaseapp.com',
    storageBucket: 'carmatchup.appspot.com',
    measurementId: 'G-SCMX8CN9VG',
  );
}
